In [ ]:
from collections import Counter
cars = ['red', 'blue', 'black', 'black', 'black', 'red', 'blue', 'red', 'white']

c = Counter(cars)

print(c.values())

In [ ]:
cars_moscow = ['black', 'black', 'white', 'black', 'black', 'white', 'yellow', 'yellow', 'yellow']
cars_spb = ['red', 'black', 'black', 'white', 'white', 'yellow', 'yellow', 'red', 'white']

mosc_count = Counter(cars_moscow)
spb_count = Counter(cars_spb)

print(mosc_count.most_common())

In [ ]:
students = [('Ivanov',1),('Smirnov',4),('Petrov',3),('Kuznetsova',1),
            ('Nikitina',2),('Markov',3),('Pavlov',2)]

groups = dict()
for student, group in students:
    if group not in groups:
        groups[group] = list()
    groups[group].append(student)

print(groups)

In [ ]:
from collections import defaultdict

gr = defaultdict(list)

for student, group in students:
    gr[group].append(student)
    
print(gr[3])


In [ ]:
from collections import OrderedDict

data = [('Ivan', 19),('Mark', 25),('Andrey', 23),('Maria', 20)]

oca = OrderedDict(sorted(data, key=lambda x: x[1]))

oca['Nikita'] = 18


print(oca)

In [ ]:
from collections import deque

clients = deque()
clients.append('Ivanov')
clients.append('Petrov')
clients.append('Smirnov')
clients.append('Tikhonova')


first_client = clients.popleft()
second_client = clients.popleft()
tired_client = clients.pop()
del clients[0]



print('First client: ', first_client)
print('Second client: ', second_client)
print(tired_client, 'has left the queue')

if not clients:
    print('No clients in queue')
    



In [ ]:
shop = deque([1, 2, 3, 4, 5])
print(shop)
shop.extendleft([6, 7, 8, 9, 10])
print(shop)

In [ ]:
lim = deque(maxlen=3)
print(lim)
limlist = deque(shop, maxlen=3)
print(limlist.append(6))
print(limlist)

In [ ]:
temps = [20.6, 19.4, 19.0, 19.0, 22.1,
        22.5, 22.8, 24.1, 25.6, 27.0,
        27.0, 25.6, 26.8, 27.3, 22.5,
        25.4, 24.4, 23.7, 23.6, 22.6,
        20.4, 17.9, 17.3, 17.3, 18.1,
        20.1, 22.2, 19.8, 21.3, 21.3,
        21.9]

days = deque(maxlen=7)
for temp in temps:
    days.append(temp)
    if len(days) == days.maxlen:
        print(round(sum(days)/len(days),2), end='; ')
print('')

In [ ]:
from collections import OrderedDict
temps = [('2000', -4.4), ('2001', -2.5), ('2002', -4.4), ('2003', -9.5)]

def check(temps):
    temp = OrderedDict(sorted(temps, key=lambda x: -x[1]))
    print(temp)
    
check(temps)

In [ ]:
from collections import deque
def brackets(line):
    line_stack = deque()
    
    for brack in line:
        if brack == '(':
            line_stack.append(brack)
        elif brack == ')':
            if len(line_stack) == 0:
                return False
            line_stack.pop()
    if len(line_stack) == 0:
        return True
    else:
        return False
            
print(brackets("(()())"))

        

In [ ]:
ratings = [('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8),
           ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1),
           ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)]

cafes = OrderedDict(sorted(ratings, key= lambda x: (x[-1], x[0])))
print(cafes)

In [ ]:
from collections import defaultdict, deque

tasks = [(36871, 'office', False),
(40690, 'office', False),
(35364, 'voltage', False),
(41667, 'voltage', True),
(33850, 'office', False)]


def task_manager(tasks):
    dic = defaultdict(deque)
    for task in tasks:
        if task[-1]:
            dic[task[1]].appendleft([task[0]])
        else:
            dic[task[1]].append([task[0]])
    return dic
     
task_manager(tasks)

    

Numpy

In [ ]:
import numpy as np

b = np.int8(124)
print(b)

np.iinfo(b)

In [ ]:
print(np.uint8(-456))

In [ ]:
arr = np.arange(8)
arr.shape = (2, 4)
arr_new = arr.reshape((2, 4),order = 'F')

arr_trans = arr.transpose()

arr_trans



In [ ]:
nd = np.linspace(0, 6, 12, endpoint=False).reshape(3,4)
nd[::-3,]

In [ ]:
nd = np.linspace(0, 6, 12, endpoint=False).reshape(3,4)
nd


In [1]:
import numpy as np
mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype=np.int16)

elem_5_3 = mystery[4,2]
last = mystery[-1, -1]
line_4 = mystery[3]
col_2 = mystery[:, -2]
part = mystery[1:5, 2]
rev = mystery[::-1,-1]
trans = mystery.transpose()

mystery.item

<function ndarray.item>

In [ ]:
zeros = np.zeros((5,4,3), dtype=np.float32)
print(zeros.shape)

In [ ]:
np.arange(5,10, 0.5)

In [ ]:
lin = np.linspace(-6,21, 6, endpoint= True, retstep=True)
lin

Length

In [ ]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1+vec2

In [ ]:
vec = np.array([3,4])
length = np.sqrt(np.sum(vec**2))
length

In [ ]:
l = np.linalg.norm(vec)
l

Distance

In [ ]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.sqrt(np.sum((vec1-vec2)**2))
distance

In [ ]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
dist = np.linalg.norm(vec1-vec2)
dist

In [ ]:
vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)
sp = np.sum(vec1*vec2)
sp

In [ ]:
scp = np.dot(vec1, vec2)
scp

In [ ]:
vec = np.array([2,7,18,28,18,1,8,4])

print(vec.mean())

In [9]:
shape = (3, 4)
np.random.sample(shape)


array([[0.61767019, 0.48680178, 0.67452364, 0.63767624],
       [0.6866627 , 0.94185969, 0.60605174, 0.24696717],
       [0.87270788, 0.80675316, 0.61340427, 0.78503847]])

In [24]:
np.random.randint(10, size= (2,3))

array([[5, 7, 2],
       [4, 0, 5]])

In [29]:
arr = np.arange(6)
print(arr)
np.random.shuffle(arr)
arr

[0 1 2 3 4 5]


array([4, 3, 5, 0, 2, 1])

In [35]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]

shuffled = np.random.permutation(playlist)
print(playlist)
print(shuffled)

['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']
['Pink Floyd' 'ACDC' 'Deep Purple' 'The Beatles']


In [39]:
np.random.permutation(10)

array([3, 4, 6, 7, 5, 0, 8, 1, 2, 9])

In [45]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']

choice = np.random.choice([1,2,3,4,5,6], 10)
print(choice)

[4 3 2 5 4 3 5 6 3 6]


In [57]:
np.random.seed(100)
np.random.randint(10, size=(3))

array([8, 8, 3])

In [84]:
np.random.seed(2021)
simple = np.random.rand()
randoms = np.random.randint(-150, 2022, size=120)
table = np.random.randint(1, 101, (3,2))
even = np.arange(2, 17, 2)
mix = np.random.permutation(even)
select = np.random.choice(even, 3, False)
triplet = np.random.permutation(select)
select

array([14,  6,  8])

Pandas